image: docker:stable

stages:
  - build
  - deploy

services:
  - docker:dind

build-docker-image:
  stage: build
  only:
    - /^(\d+)\.(\d+)\.(\d+)$/
    - develop
    - /^feature\/(.*)$/
    - /^bugfix\/(.*)$/
  script:
    - docker run --rm mikesir87/aws-cli:latest aws ecr get-login --region us-west-2 --no-include-email | sh
    - DOCKER_TAG=$(echo $CI_COMMIT_REF_NAME | sed 's;/;-;g')
    - FEATURE=$(echo $DOCKER_TAG | sed 's;^feature/;;g')
    - DOCKER_REF=$AWS_DOCKER_REGISTRY_URL/blockchain-terminal-ui:$DOCKER_TAG
    - docker build --build-arg COMMIT=${CI_COMMIT_SHA} -t $DOCKER_REF -f deployment/Dockerfile .
    - docker push $DOCKER_REF
    - docker rmi $DOCKER_REF

apply-kubernetes-resources:
  stage: deploy
  image: pavelkhritonenko/aws-kubectl
  only:
    - /^feature\/(.*)$/
    - /^bugfix\/(.*)$/
  script:
    - DOCKER_TAG=$(echo $CI_COMMIT_REF_NAME | sed 's;/;-;g')
    - aws eks --region us-west-2 update-kubeconfig --name prod-bct-tools
    - FEATURE=$(echo $DOCKER_TAG | sed 's;^feature-;;g' | sed 's;^bugfix-;;g')
      COMMIT=$CI_COMMIT_SHORT_SHA
      DOCKER_REF=$AWS_DOCKER_REGISTRY_URL/blockchain-terminal-ui:$DOCKER_TAG
      envtpl ./deployment/deployment.tpl.yaml | kubectl apply -f -
    - (cd ./deployment && ./collectObsoleteDeployments.sh)
